name: edu_link
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_facebook_auth: ^7.1.1

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.1
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.6.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/database/
    - assets/images/
flutter_intl:
  enabled: true
