name: edu_link
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  file_picker: ^10.1.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  go_router: ^15.0.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.2
  smart_notification_manager: ^0.0.5
  supabase_flutter: ^2.6.3
  syncfusion_flutter_pdfviewer: ^29.1.38
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/database/
    - assets/images/
    - assets/service_account.json

flutter_intl:
  enabled: true
