name: edu_link
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
